---
- name: Check if temporary directory already exists
  stat: path={{ download_dir }}
  register: tmp

- name: Create temporary download directory
  file: name={{ download_dir }} state=directory
  when: tmp.stat.exists == false

- name: Download pip installer
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest={{ download_dir }}

- name: Get full path of download directory ("~" varies by user)
  shell: pwd
  args:
    chdir: "{{ download_dir }}"
  register: pwd_result 

- name: Install pip
  become: true
  command: python3 {{ pwd_result.stdout }}/get-pip.py

- name: Remove temporary download directory, if it didn't prevously exist
  file: name={{ download_dir }} state=absent
  when: tmp.stat.exists == false

- name: Install virtualenv and virtualenvwrapper
  become: true
  pip: name={{ item }} executable=pip3
  with_items:
  - virtualenv
  - virtualenvwrapper

- name: Update .bashrc with virtualenvwrapper
  lineinfile:
    backup=yes
    create=true
    dest=~/.bashrc
    insertafter=EOF
    line={{ item }}
    state=present
  with_items:
  - export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
  - export WORKON_HOME={{ virtualenv_home }}
  - source /usr/local/bin/virtualenvwrapper.sh

- name: Create a new Python virtual environment
  shell: |
    source /usr/local/bin/virtualenvwrapper.sh
    mkvirtualenv {{ virtualenv_name }}
  args:
    executable: /bin/bash

- name: Install numpy
  command: "{{ virtualenv_home }}/{{ virtualenv_name}}/bin/pip install numpy"

